cli:
  name: Test
  command: hexagon-test
  custom_tools_dir: .

envs:
  - name: dev
    alias: d
    long_name: dev
  - name: qa
    alias: q
    long_name: qa

tools:

  - name: p-m-args
    action: python_module_args
    type: shell
    alias: pma
    long_name: Python Module Script With Args

  - name: only-optionals
    action: python_module_only_optionals
    type: shell
    alias: oo
    long_name: Python Module Script With Only Optional Args

  - name: no-args
    action: python_module_no_args
    type: shell
    alias: na
    long_name: Python Module Script With No Args

  - name: access-multiple-times
    action: python_module_access_multiple_times
    type: shell
    alias: amt
    long_name: Python Module Script With Multiple Arg Access