cli:
  name: Test
  command: hexagon-test
  custom_tools_dir: .

envs:
  - name: dev
    alias: d
    long_name: dev
  - name: qa
    alias: q
    long_name: qa

tools:
  - name: google
    long_name: Google
    type: web
    action: open_link
    envs:
      "*": https://www.google.com/

  - name: python-module
    action: python_module
    type: shell
    alias: pm
    long_name: Python Module Test

  - name: python-module-env
    action: python_module
    type: shell
    alias: pme
    long_name: Python Module Env Test
    envs:
      dev:
        - 789
        - ghi
      qa:
        foo: foo
        bar: bar

  - name: python-module-env-all
    action: python_module
    type: shell
    alias: python-module-env-all
    long_name: Python Module Asterisk Env Test
    envs:
      "*": all_envs

  - name: node-module
    action: node-module.js
    type: shell
    alias: nm
    long_name: Node Module Test

  - name: node-module-env
    action: node-module.js
    type: shell
    alias: nme
    long_name: Node Module Env Test
    envs:
      dev:
        - 789
        - ghi
      qa:
        foo: foo
        bar: bar

  - name: single-file-python-module
    action: single_file_module
    type: shell
    alias: sfpm
    long_name: Python Module Single File Test