cli:
  name: Test
  command: hexagon-test
  custom_tools_dir: .

envs:
  - name: dev
    alias: d
    long_name: dev

tools:

  - name: prompt-skip-trace-test
    action: test_skip_trace
    type: shell
    alias: pstt
