cli:
  name: Test
  command: hexagon-test
  custom_tools_dir: .

envs:
  - name: dev
    alias: d
    long_name: dev
  - name: qa
    alias: q
    long_name: qa

tools:
  - name: generic-command
    action: 'echo "executed generic-command"'
    type: shell
    alias: gc
    long_name: A generic command

  - name: complex-command
    action: 'echo "nested $(echo 1)"'
    type: shell
    alias: cc
    long_name: A complex command

  - name: complex-command-with-dots
    action: 'cat some_file.txt | xargs echo "with . dots"'
    type: shell
    alias: ccd
    long_name: A complex command with dots

  - name: generic-multiline-command
    action: |
      echo "executed generic-multiline-command #1"
      echo "executed generic-multiline-command #2"
      echo "executed generic-multiline-command #3"
    type: shell
    alias: gmc
    long_name: A generic multinline command

  - name: failing-command
    action: i-dont-exist
    type: shell
    alias: fc
    long_name: A failing command

  - name: p-m-import-error
    action: p_m_import_error
    type: shell
    alias: pmie
    long_name: Python Module Import Error Test

  - name: p-m-script-error
    action: p_m_script_error
    type: shell
    alias: pmse
    long_name: Python Module Script Error Test