cli:
  name: Test
  custom_tools_dir: .
  command: [ 'test' ]

tools:

  - name: google-valid
    long_name: Google
    type: web
    action: 'open_link'
    envs:
      '*': https://www.google.com/

  - name: google-invalid
    long_name: Google
    type: web

  - name: another-invalid
    long_name: Google 2
    type: web
    action: