cli: 
  name: Test
  custom_tools_dir: .

tools:
  google-invalid:
    long_name: Google
    type: web

  google-valid:
    long_name: Google
    type: web
    action: 'open_link'
    envs:
      '*': https://www.google.com/