cli: 
  name: Test
  custom_tools_dir: .

tools:
  - name: google-invalid
    long_name: Google
    type: web

  - name: google-valid
    long_name: Google
    type: web
    action: 'open_link'
    envs:
      '*': https://www.google.com/