cli: 
  name: Test
  command: hexagon-test
  entrypoint:
    pre_command: pipenv run
  custom_tools_dir: .

tools:
  - name: google
    long_name: Google
    type: web
    action: 'open_link'
    envs:
      '*': https://www.google.com/

envs:
  - name: dev
    alias: d