cli: 
  name: Test
  command: hexagon-test

tools:
  - name: google
    long_name: Google
    type: web
    action: 'open_link'
    envs:
      '*': https://www.google.com/

envs:
  - name: dev
    alias: d