name: 02_guidelines

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: versions
        name: get tools versions from lock file
        run: |
          echo "black=$(cat Pipfile.lock | jq -r '.develop.black.version' | sed 's/==//g')" >> $GITHUB_OUTPUT
          echo "flake8=$(cat Pipfile.lock | jq -r '.develop.flake8.version' | sed 's/==//g')" >> $GITHUB_OUTPUT
          echo "bugbear=$(cat Pipfile.lock | jq -r '.develop."flake8-bugbear".version' | sed 's/==//g')" >> $GITHUB_OUTPUT

      - uses: psf/black@stable
        with:
          version: ${{ steps.versions.outputs.black }}

      - uses: TrueBrain/actions-flake8@v2.3
        with:
          flake8_version: ${{ steps.versions.outputs.flake8 }}
          plugins: flake8-bugbear==${{ steps.versions.outputs.bugbear }}