name: guidelines

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: TrueBrain/actions-flake8@v2.1
        with:
          plugins: flake8-bugbear
