# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y gettext
          python -m pip install --upgrade pipenv
          pipenv install --dev --ignore-pipfile

      - name: Unit tests
        run: |
          pipenv run pytest -svv tests/

      - name: Setup e2e dependencies
        run: |
          python -m pip install wheel
          .github/scripts/i18n/build.sh
          python setup.py sdist bdist_wheel
          python -m pip install --find-links=./dist hexagon

      - uses: actions/upload-artifact@v2
        with:
          name: hexagon
          path: dist/*.tar.gz

      - name: e2e tests
        run: |
          pipenv run pytest -svv e2e/

  i18n:
    name: i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install gettext
        run: sudo apt-get install -y gettext

      - name: add matcher
        run: echo "::add-matcher::.github/i18n-problem-matcher.json"

      - name: build locales
        run: .github/scripts/i18n/build.sh

      - name: validate translations
        run: .github/scripts/i18n/check.sh

      - name: remove matcher
        run: echo "::remove-matcher owner=hexagon-i18n::"

  release:
    if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}

    runs-on: ubuntu-latest
    needs: [test, i18n]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install gettext
        run: sudo apt-get install -y gettext

      - name: build locales
        run: .github/scripts/i18n/build.sh

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          pypi_token: ${{ secrets.PYPI_TOKEN }}