name: guidelines

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: versions
        name: Find black version from lock file
        run: |
          echo "::set-output name=black::$(cat Pipfile.lock | jq -r '.develop.black.version' | sed 's/==//g')"
          echo "::set-output name=flake8::$(cat Pipfile.lock | jq -r '.develop.flake8.version' | sed 's/==//g')"
          echo "::set-output name=bugbear::$(cat Pipfile.lock | jq -r '.develop."flake8-bugbear".version' | sed 's/==//g')"
      - uses: psf/black@stable
        with:
          version: ${{ steps.versions.outputs.black }}

      - uses: TrueBrain/actions-flake8@v2.1
        with:
          flake8_version: ${{ steps.versions.outputs.flake8 }}
          plugins: flake8-bugbear==${{ steps.versions.outputs.bugbear }}