# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci/cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get install -y gettext
          python -m pip install --upgrade pipenv
          pipenv install --dev --ignore-pipfile

      - name: Unit tests
        run: |
          pipenv run pytest -svv tests/

      - uses: ./.github/actions/download-i18n

      - name: build artifact
        run: |
          python -m pip install wheel
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: hexagon
          path: dist/*.tar.gz

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [ i18n, build ]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v3
        with:
          name: hexagon
          path: dist

      - uses: ./.github/actions/download-i18n

      - name: Setup e2e dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          python -m pip install --find-links=./dist hexagon

      - name: e2e tests
        run: |
          pytest -svv e2e/ --junitxml=junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml

  i18n:
    name: i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install gettext
        run: sudo apt-get install -y gettext

      - name: add matcher
        run: echo "::add-matcher::.github/i18n-problem-matcher.json"

      - name: build locales
        run: .github/scripts/i18n/build.sh

      - name: validate translations
        run: .github/scripts/i18n/check.sh

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: i18n
          path: locales/**/*.mo

      - name: remove matcher
        run: echo "::remove-matcher owner=hexagon-i18n::"

  release:
    if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}

    runs-on: ubuntu-latest
    needs: [ build, test, i18n ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.USER_TOKEN }}

      - uses: ./.github/actions/download-i18n

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.USER_TOKEN }}
#          pypi_token: ${{ secrets.PYPI_TOKEN }}