name: 'Test Report'

on:
  workflow_run:
    workflows: [ '01_ci-cd' ]
    types:
      - completed
    branches:
      - main

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: /(.*)-test-results-(.*)/
          name: Pytest Tests
          path: '*.xml'
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false
