name: 'Test Report'

on:
  workflow_run:
    workflows: [ 'ci/cd' ]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /test-results-(.*)/
          name: Pytest Tests
          path: '*.xml'
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false
